version: '3.3'
services:

  product:
    image: product
    environment:
      PROCESS_TYPE: web
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: product
      DB_PORT: 5432
    ports:
      - 3000:3000
    links:
      - db

  db:
    image: postgres:10.4-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: product

  migrate_data:
    image: product
    environment:
      PROCESS_TYPE: script
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: product
      DB_PORT: 5432
    links:
      - db
    depends_on:
      - db
    command: >
      /bin/sh -c "
        while ! nc -z -w1 db 5432;
        do
          echo sleeping;
          sleep 1;
        done;
        echo Connected!;
        node index.js
      "