kind: Pod
apiVersion: v1
metadata:
  name: product-db
  labels:
    app: product-db
spec:
  containers:
    - name: product-db
      image: postgres:10.4-alpine
      imagePullPolicy: Always
      ports:
        - containerPort: 5432
          name: product-db
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: product
              key: db_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: product
              key: db_password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: product
              key: db_database